### ISSUE TITLE
支持预加载吗？

### ISSUE THREAD

**Issue by chiaweilee** [ctq123/ant-virtual-table#10]
比如，每页 10 条时，预先加载 上/下 10条数据，这样滚动式渲染更流畅一些

**Comment by ctq123** [comment]
其实里面有这种处理的，预留上下五条的数据“预加载”。但其实问题并不在这，试想一下，假如有100w+数据呢？上下滑动一丢丢，就是滑动几千条的数据了。

其实只要css样式设置合理的话，看得到的那个窗口应该不会溢出的。

gif动画中之所以有空白的现象，其实是录制工具的问题，滑动过快，录制工具没法把所有的帧都补全，就会有空白现象，如有兴趣可以试下我给的那个1000w数据的例子，会比例子中的动画好很多。
