### ISSUE TITLE
全选时只选择了渲染的节点

### ISSUE THREAD

**Issue by hejinhua** [ctq123/ant-virtual-table#13]
使用虚拟滚动时，点击全选只选择了渲染出来的dom节点，滚动滚动条时，后面的数据都没有选中

**Comment by andyyxw** [comment]
确实是，是bug还是没有这个功能？

**Comment by yiyizym** [comment]
自己重写一下 rowSelection 的 onSelectAll 方法就可以解决

**Comment by jsonshao** [comment]
我也有这个问题，怎么解决的大神

**Comment by jsonshao** [comment]
> 自己重写一下 rowSelection 的 onSelectAll 方法就可以解决

怎么重写的

**Comment by ctq123** [comment]
版本0.1.7已解决，请升级 @hejinhua @jsonshao

**Comment by jsonshao** [comment]
> 版本0.1.7已解决，请升级 @hejinhua @jsonshao

如果固定前3列，滚动就会有问题

**Comment by jsonshao** [comment]
> > 版本0.1.7已解决，请升级 @hejinhua @jsonshao
> 
> 如果固定前3列，滚动就会有问题

而且有点抖动

**Comment by jsonshao** [comment]
> > > 版本0.1.7已解决，请升级 @hejinhua @jsonshao
> > 
> > 
> > 如果固定前3列，滚动就会有问题
> 
> 而且有点抖动

固定列的行不会随着滚动有点问题啊

**Comment by ctq123** [comment]
ant-virtual-table@0.1.9版本中已解决固定列的问题
