### ISSUE TITLE
大佬能不能支持下复选框全选，目前是有问题的，感谢大佬

### ISSUE THREAD

**Issue by running-snail-sfs** [ctq123/ant-virtual-table#16]

**Comment by ctq123** [comment]
你好，你是不是没有升级版本。全选的问题已处理#13

**Comment by ctq123** [comment]
全选若还有问题，请详细描述一下，或者用https://codepen.io/pen/在线描述具体的demo

**Comment by running-snail-sfs** [comment]
> 全选若还有问题，请详细描述一下，或者用https://codesandbox.io/s/antdxunibiao-demo-rj5qc?file=/index.js 在线描述具体的demo

https://codesandbox.io/s/antd-reproduction-template-fvm30?file=/package.json 依然有问题，直选中了渲染的节点

**Comment by ctq123** [comment]
@running-snail-sfs 亲，是你用法不对（或者说不规范），具体可以仔细看下antd3.x的API，全选的api是onSelectAll，而不是onChange。onChange是监听当前渲染dom出现变化change的回调，如果其他dom都没有渲染出来，它是监听不到的。这时应该遵循规范来监听onSelectAll的回调。如下：
```js
const rowSelection = {
      selectedRowKeys,
      onChange: (keys, rows) => {
        console.log("keys=, rows=", keys, rows);
        this.setState({
          selectedRowKeys: keys,
          selectedRowData: rows
        });
      },
      onSelectAll: (selected, selectedRows) => {
        console.log(
          `onSelectAll selected: ${selected}`,
          "selectedRows: ",
          selectedRows
        );
      },
    };
```

**Comment by running-snail-sfs** [comment]
好的，我试试




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Alan"<notifications@github.com&gt;; 
发送时间: 2020年4月20日(星期一) 晚上6:03
收件人: "ctq123/ant-virtual-table"<ant-virtual-table@noreply.github.com&gt;; 
抄送: "742410510"<742410510@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [ctq123/ant-virtual-table] 大佬能不能支持下复选框全选，目前是有问题的，感谢大佬 (#16)





 
@running-snail-sfs 亲，是你用法不对（或者说不规范），具体可以仔细看下antd3.x的API，全选的api是onSelectAll，而不是onChange。onChange是监听当前渲染dom出现变化change的回调，如果其他dom都没有渲染出来，它是监听不到的。这时应该遵循规范来监听onSelectAll的回调。如下：
 const rowSelection = {       selectedRowKeys,       onChange: (keys, rows) =&gt; {         console.log("keys=, rows=", keys, rows);         this.setState({           selectedRowKeys: keys,           selectedRowData: rows         });       },       onSelectAll: (selected, selectedRows) =&gt; {         console.log(           `onSelectAll selected: ${selected}`,           "selectedRows: ",           selectedRows         );       },     };

**Comment by running-snail-sfs** [comment]
大佬，antd 3.26.14不支持了，能否支持下


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ctq123/ant-virtual-table"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年4月19日(星期天) 下午4:37
收件人:&nbsp;"ctq123/ant-virtual-table"<ant-virtual-table@noreply.github.com&gt;;
抄送:&nbsp;"742410510"<742410510@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ctq123/ant-virtual-table] 大佬能不能支持下复选框全选，目前是有问题的，感谢大佬 (#16)





 
全选若还有问题，请详细描述一下，或者用https://codepen.io/pen/在线描述具体的demo
