### ISSUE TITLE
编译后的代码导致对 antd 的全量引用

### ISSUE THREAD

**Issue by jackyking-cn** [ctq123/ant-virtual-table#18]
源码中：
`import { Table } from 'antd'`

被编译成：
`var _antd = require('antd');`
`// ...`
`return _react2.default.createElement(_antd.Table, _extends({}, rest, {
        rowSelection: newRowSelection,
        dataSource: renderSource
      }));
`
导致项目打包时全量引入 antd 代码。

建议改为按需使用：
`import Table from 'antd/es/table'`
或者配置  [babel-plugin-import](https://github.com/ant-design/babel-plugin-import)  自动处理。

**Comment by ctq123** [comment]
哦，外面项目引用babel-plugin-import没有注意到组件内部里面的问题，没有考虑外部项目没有配置，babel-plugin-import的场景，ant-virtual-table@0.1.10已修复，谢谢提醒～
