### ISSUE TITLE
引入后存在样式被覆盖

### ISSUE THREAD

**Issue by Da-Sheng** [ctq123/ant-virtual-table#23]
做的项目更换了antd的主题色
在引入ant-virtual-table后，主题色被覆盖了，为默认的蓝色，暂时发现button和a标签等
是否可以避开样式的引用呢

**Comment by zjhcute** [comment]
遇到相同的问题，引入ant-virtual-table后，主题色被覆盖

**Comment by ctq123** [comment]
v0.1.11版本已修复，升级最新版本试试 @Da-Sheng @zjhcute
