### ISSUE TITLE
合并滚动的时候错位

### ISSUE THREAD

**Issue by jsonshao** [ctq123/ant-virtual-table#6]
- 
![image](https://user-images.githubusercontent.com/29230698/60936331-4d5fe080-a2ff-11e9-94d0-5e1471b1bf2f.png)
![image](https://user-images.githubusercontent.com/29230698/60936340-53ee5800-a2ff-11e9-9582-56e671aab6f9.png)

**Comment by ctq123** [comment]
滚动错位的问题是ant Table本身的bug，可以试试这个
.ant-table-fixed {
  table-layout: fixed;
}

.ant-table-tbody > tr > td {
  word-wrap: break-word;
  word-break: break-all;
}
